### ISSUE TITLE
Application request: Bitwarden CLI

### ISSUE THREAD

**Issue by broizter** [whalehub/ginstall.sh#1]
I would like to get support for BitWardens CLI utility. https://github.com/bitwarden/cli

I love this script you have written btw since it solves a problem I've had. I will look into the code soon and maybe submit pull requests for other applications!

**Comment by whalehub** [comment]
@broizter I just published `ginstall.sh` [v1.4.0](https://github.com/whalehub/ginstall.sh/releases/tag/v1.4.0) with support for Bitwarden CLI. 🎉
