### ISSUE TITLE
Can't install youtube-dl

### ISSUE THREAD

**Issue by toomyem** [whalehub/ginstall.sh#14]
While trying to install youtube-dl, I'm getting the following error:

```
$ sudo ginstall.sh youtube-dl 2020.06.16.1
gget: error: target file already specified: /usr/local/bin/youtube-dl
```

I'm using the following ginstall.sh version:
```
$ ginstall.sh -v
ginstall.sh version 3.1.0 linux/amd64
```

**Comment by whalehub** [comment]
@toomyem It looks like they added a new resource type to their releases which needs to be excluded. Just published [v3.3.1](https://github.com/whalehub/ginstall.sh/releases/tag/v3.3.1) with a fix for this issue. 🎉
