### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by AzureCerulean** [whalehub/ginstall.sh#4]
404 Not Found

For all apps tested.

ex:

gget: error: resolving ref: getting latest release: GET https://api.github.com/repos/ytdl-org/youtube-dl2020.06.06/releases/latest: 404 Not Found []

or

ginstall.sh ffmpeg 4.2.3

...

curl: (22) The requested URL returned error: 404

[
√ ginstall.sh done (sha256 OK)
ginstall.sh successfully updated itself to the latest version (v2.0.1).
]

**Comment by whalehub** [comment]
@AzureCerulean Thank you for reporting this! Just published [v2.0.2](https://github.com/whalehub/ginstall.sh/releases/tag/v2.0.2) with a fix for both issues.
