### ISSUE TITLE
Application request: drive

### ISSUE THREAD

**Issue by gokulsoumya** [whalehub/ginstall.sh#6]
From the [GitHub page](https://github.com/odeke-em/drive):

> `drive` is a tiny program to pull or push Google Drive files.

P.S. Thanks for writing this. Saves me (and a lot of people I'm sure) a ton of pain in keeping the programs updated. Keep up the good work !

**Comment by whalehub** [comment]
@gokulsoumya Just published [v2.4.0](https://github.com/whalehub/ginstall.sh/releases/tag/v2.4.0) with support for this application. 🚀 

P.S.: You're welcome!
