### ISSUE TITLE
Various requests

### ISSUE THREAD

**Issue by HugLifeTiZ** [whalehub/ginstall.sh#9]
Hi there! Thanks for your work on this. I have a few requests:

Borg: https://github.com/borgbackup/borg
Handlr: https://github.com/chmln/handlr
JQ: https://github.com/stedolan/jq
Pegasus Frontend: https://github.com/mmatyas/pegasus-frontend
Unetbootin: https://github.com/unetbootin/unetbootin

RPCS3: https://github.com/RPCS3/rpcs3
This one is probably going to be more complex because it recommends the AppImage downloads from its main downloads page.

**Comment by whalehub** [comment]
@HugLifeTiZ Just published [v2.7.0](https://github.com/whalehub/ginstall.sh/releases/tag/v2.7.0) with support for the first five. I probably won't be adding support for RPCS3 since AppImages have libfuse as an external dependency (among other reasons).
